name: SoftLimit
main: org.kitteh.softlimit.SoftLimit
version: 1.0
author: mbaxter
description: Allow special members to join no matter the player count
website: http://kitteh.org
permissions:
  softlimit.bypass:
    description: Enter a server at all times
    default: op